# Generated by Django 5.0.6 on 2025-01-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobbids_bit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbids',
            name='bit_type',
        ),
        migrations.AddField(
            model_name='jobbids',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/bids/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='bit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
