# Generated by Django 3.2.15 on 2024-04-16 07:45

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_useractivation_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2024, 4, 16, 7, 45, 8, 482778, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
