# Generated by Django 3.2.15 on 2024-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240416_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=255),
        ),
    ]
