# Generated by Django 3.2.15 on 2024-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='otp',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
