# Generated by Django 5.0.6 on 2024-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_useractivation_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'supplier'), ('client', 'client'), ('admin', 'Admin')], default='client', max_length=255),
        ),
    ]
