# Generated by Django 3.2.15 on 2023-11-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0004_userprofile_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='notification_images/')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('plain_text', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_updated_at', models.DateTimeField(auto_now=True)),
                ('notification_is_read', models.BooleanField(default=False)),
                ('notification_is_deleted', models.BooleanField(default=False)),
                ('notification_is_archived', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to='userprofile.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='userprofile.userprofile')),
            ],
        ),
    ]
