# Generated by Django 5.0.6 on 2025-03-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '__first__'),
        ('dashboard', '0001_initial'),
        ('helpandsupport', '0001_initial'),
        ('services', '0002_alter_services_tags'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='notification_images/')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('plain_text', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_updated_at', models.DateTimeField(auto_now=True)),
                ('notification_is_read', models.BooleanField(default=False)),
                ('notification_is_deleted', models.BooleanField(default=False)),
                ('notification_is_archived', models.BooleanField(default=False)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_notification', to='chat.roommessage')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_notification', to='dashboard.orders')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to='userprofile.userprofile')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notification', to='helpandsupport.report')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='userprofile.userprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_notification', to='services.services')),
            ],
        ),
    ]
