# Generated by Django 3.2.15 on 2024-06-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0004_report_email'),
        ('notification', '0006_alter_notificationdetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetails',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notification', to='helpandsupport.report'),
        ),
    ]
