# Generated by Django 3.2.15 on 2024-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20240419_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        # migrations.AddField(
        #             model_name='subcategories',
        #             name='subcategory_slug',
        #             field=models.SlugField(default=1, max_length=100, unique=True),
        #             preserve_default=False,
        #         ),

    ]
