# Generated by Django 3.2.15 on 2024-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20240425_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
