# Generated by Django 5.0.6 on 2024-08-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_subcategories_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('blog', 'blog'), ('service', 'service')], default='blog', max_length=100),
        ),
    ]
