# Generated by Django 5.0.6 on 2025-02-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_categories_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
