# Generated by Django 3.2.15 on 2024-04-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_name',
        ),
    ]
