# Generated by Django 5.0.6 on 2025-02-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0004_report_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'News Letter',
                'verbose_name_plural': 'News Letters',
                'db_table': 'news_letters',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='news_letter_id_cafbab_idx'), models.Index(fields=['-created_at'], name='news_letter_created_2de71a_idx')],
            },
        ),
    ]
