# Generated by Django 5.0.6 on 2025-03-04 16:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '__first__'),
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('service_slug', models.SlugField(max_length=255, unique=True)),
                ('service_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='services')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='services/attachments/')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('availability_start_time', models.TimeField(blank=True, null=True)),
                ('availability_end_time', models.TimeField(blank=True, null=True)),
                ('availability_days', models.CharField(choices=[('all_days', 'All Days'), ('week_days', 'Week Days'), ('weekend', 'Weekend')], default='all_days', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicesCurrency', to='assets.currency')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicesSubcategories', to='assets.subcategories')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicesSupplier', to='userprofile.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('cost_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='applications/attachments/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='userprofile.userprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.services')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
            },
        ),
    ]
