# Generated by Django 3.2.15 on 2024-04-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20240419_1243'),
        ('services', '0002_alter_services_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicesCurrency', to='assets.currency'),
        ),
    ]
