# Generated by Django 3.2.15 on 2024-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
