# Generated by Django 3.2.15 on 2024-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=255),
        ),
    ]
