# Generated by Django 3.2.15 on 2024-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
