# Generated by Django 5.0.6 on 2024-08-15 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_services_availability_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='services/attachments/'),
        ),
        migrations.AddField(
            model_name='services',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
    ]
