# Generated by Django 5.0.6 on 2024-08-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_services_description'),
        ('userprofile', '0015_alter_businessprofile_business_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('cost_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='applications/attachments/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='userprofile.userprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.services')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
            },
        ),
    ]
