# Generated by Django 5.0.6 on 2024-11-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
