# Generated by Django 3.2.15 on 2024-04-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
