# Generated by Django 3.2.15 on 2024-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20240425_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouproommessage',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
