# Generated by Django 3.2.15 on 2024-04-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0001_initial'),
        ('chat', '0004_grouproommessage_is_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouproommessage',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_ws_room_messages', to='helpandsupport.report'),
        ),
    ]
