# Generated by Django 3.2.15 on 2024-05-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0003_auto_20240429_1307'),
        ('userprofile', '0009_alter_userprofile_phone'),
        ('chat', '0007_alter_roommessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocked_rooms', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='room',
            name='dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_rooms', to='helpandsupport.report'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='cleared_by',
            field=models.ManyToManyField(blank=True, related_name='cleared_room_messages', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
