# Generated by Django 3.2.15 on 2024-05-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0003_auto_20240429_1307'),
        ('chat', '0008_auto_20240530_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dispute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_rooms', to='helpandsupport.report'),
        ),
    ]
