# Generated by Django 5.0.6 on 2025-03-13 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_jobs_tags'),
        ('services', '0002_alter_services_tags'),
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_custom_offer', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('payment_via', models.CharField(blank=True, choices=[('paypal', 'Paypal'), ('stripe', 'Stripe')], max_length=255, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('in_progress', 'in_progress'), ('in_revision', 'In Revision'), ('withdraw', 'Withdraw')], default='in_progress', max_length=25)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'overdue'), ('partial_paid', 'Partial Paid')], default='pending', max_length=255)),
                ('is_paid_service_fee', models.BooleanField(default=False)),
                ('hiring_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_offer', to='userprofile.userprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='jobs.jobbids')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_offer', to='services.services')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback', to='dashboard.orders')),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback_supplier', to='dashboard.orders')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_feedback', to='services.services')),
            ],
            options={
                'verbose_name': 'Supplier Feedback',
                'verbose_name_plural': 'Supplier Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
