# Generated by Django 3.2.15 on 2024-04-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='services',
            new_name='service',
        ),
    ]
