# Generated by Django 3.2.15 on 2024-04-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_service_slug'),
        ('dashboard', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='client',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='for_client',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='for_supplier',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='services',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='supplier',
        ),
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_feedback', to='services.services'),
        ),
    ]
