# Generated by Django 3.2.15 on 2024-04-29 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20240429_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback', to='dashboard.orders')),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
