# Generated by Django 3.2.15 on 2024-04-30 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_service_slug'),
        ('userprofile', '0008_auto_20240429_1307'),
        ('dashboard', '0005_auto_20240429_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='is_payment',
            new_name='is_service_fee',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'overdue')], default='pending', max_length=255),
        ),
        migrations.CreateModel(
            name='SupplierFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientFeedback', to='userprofile.userprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_feedback', to='services.services')),
            ],
            options={
                'verbose_name': 'Supplier Feedback',
                'verbose_name_plural': 'Supplier Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
