# Generated by Django 3.2.15 on 2024-04-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20240430_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='is_service_fee',
            new_name='is_paid_service_fee',
        ),
    ]
