# Generated by Django 3.2.15 on 2024-05-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20240517_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
