# Generated by Django 3.2.15 on 2024-05-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20240517_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierfeedback',
            name='client',
        ),
        migrations.AddField(
            model_name='supplierfeedback',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback_supplier', to='dashboard.orders'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback', to='dashboard.orders'),
        ),
    ]
