# Generated by Django 3.2.15 on 2024-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20240520_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
