# Generated by Django 3.2.15 on 2024-05-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_alter_userprofile_phone'),
        ('dashboard', '0011_orders_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_offer', to='userprofile.userprofile'),
        ),
    ]
