# Generated by Django 5.0.6 on 2024-12-30 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_orders_client'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='jobs.jobs'),
        ),
    ]
