# Generated by Django 5.0.6 on 2025-01-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_orders_job'),
        ('jobs', '0003_jobbids_bit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='jobs.jobbids'),
        ),
    ]
