# Generated by Django 5.0.6 on 2025-01-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_orders_job'),
        ('services', '0013_alter_services_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_offer', to='services.services'),
        ),
    ]
