# Generated by Django 5.0.6 on 2024-08-08 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_categories_category_type'),
        ('blog', '0004_rename_category_blogcategory_and_more'),
        ('userprofile', '0015_alter_businessprofile_business_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='assets.categories'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
