# Generated by Django 5.0.6 on 2025-01-02 20:15

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_blog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_organizer', models.CharField(max_length=255)),
                ('organizer_contact', models.CharField(max_length=255)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_website', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'events',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.CreateModel(
            name='EventBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('no_of_tickets', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='blog.events')),
            ],
            options={
                'verbose_name_plural': 'Event Bookings',
                'db_table': 'event_bookings',
            },
        ),
    ]
