# Generated by Django 5.0.6 on 2025-01-25 03:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_slug_alter_blogpost_title'),
        ('userprofile', '0016_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/thumbnails/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
            options={
                'verbose_name_plural': 'News And Updates',
                'db_table': 'news_and_updates',
            },
        ),
    ]
