# Generated by Django 3.2.15 on 2024-04-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20240419_1243'),
        ('userprofile', '0005_auto_20240419_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_countries', to='assets.countries'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country_codes', to='assets.callingcodewithname'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_timezones', to='assets.countrytimezone'),
        ),
    ]
