# Generated by Django 5.0.6 on 2024-06-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20240604_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_business_profiles', to='userprofile.businessprofile'),
        ),
    ]
